"use strict";

module.exports = {
    "GET_HEALTH": { "supported": true },
    "GET_FLAGS": { "supported": true },
    "GET_VERSION": { "supported": true },
    "GET_METRICS": { "supported": true },
    "GET_LOGGING_LEVEL": { "supported": true },
    "SET_LOGGING_LEVEL": { "supported": false },
    "LIST_FILES": { "supported": false },
    "READ_FILE": { "supported": false },
    "GET_STATE": { "supported": true },
    "GET_AGENTS": { "supported": true },
    "GET_FRAMEWORKS": { "supported": true },
    "GET_EXECUTORS": { "supported": true },
    "GET_TASKS": { "supported": true },
    "GET_ROLES": { "supported": true },
    "GET_WEIGHTS": { "supported": true },
    "UPDATE_WEIGHTS": { "supported": false },
    "GET_MASTER": { "supported": true },
    "RESERVE_RESOURCES": { "supported": false },
    "UNRESERVE_RESOURCES": { "supported": false },
    "CREATE_VOLUMES": { "supported": false },
    "DESTROY_VOLUMES": { "supported": false },
    "GET_MAINTENANCE_STATUS": { "supported": true },
    "GET_MAINTENANCE_SCHEDULE": { "supported": true },
    "UPDATE_MAINTENANCE_SCHEDULE": { "supported": false },
    "START_MAINTENANCE": { "supported": false },
    "STOP_MAINTENANCE": { "supported": false },
    "GET_QUOTA": { "supported": true },
    "SET_QUOTA": { "supported": false },
    "REMOVE_QUOTA": { "supported": false }
};